### ISSUE TITLE
Possibilities for Including the Adjoint Method

### ISSUE THREAD

**Issue by eozd** [titu1994/tfdiffeq#2]
Hi,

In the readme you mention that adjoint method is not yet available due to limitations of tensorflow. I would like to ask a status update on this, i.e. do you have any ideas how one can incorporate the adjoint method into this tensorflow implementation? Or do you think that is entirely impossible in the current version of tensorflow?

Thanks and kind regards

**Comment by titu1994** [comment]
It is definitely possible to implement in general. However, I am unable to implement it in the context of the framework that has been developed. 

I'm not experienced enough in manipulating a custom gradient on Tensorflow.

**Comment by renmengye** [comment]
Could you describe what exactly is the problem and have an example snippet? Based on the your description I understood, TF custom gradient should allow you to define the gradients to the variables created inside, no?
